def env_check
    if (ENV['STEM'] != __dir__)
        abort "Bootenv and retry!"
        false
    else
        puts "\e[32mPASSED\e[0m -> Bootenv check"
        true
    end
end

def parse_global_features(source_path)
  features = []
  raw_values = {}
  File.readlines(source_path).each do |line|
    next unless line =~ /^\s*feature\s+['"]([^'"]+)['"]\s*,\s*(.+?)(?:\s*(?:#.*)?)$/
    raw_values[$1] = $2.strip
  end

  parser = Object.new
  parser.define_singleton_method(:component) do |*_args, &block|
    instance_eval(&block) if block
  end

  parser.define_singleton_method(:feature) do |name, value|
    features << {
      name: name.to_s,
      value: value,
      raw_value: raw_values[name.to_s]
    }
  end

  parser.instance_eval(File.read(source_path), source_path)
  features
rescue SyntaxError, StandardError => e
  abort "Failed to parse feature file #{source_path}: #{e.class}: #{e.message}"
end

require 'fileutils'

def format_feature_value(value, raw_value)
  if value.is_a?(String)
    value.inspect
  elsif raw_value && raw_value.match?(/^\s*-?(?:0x[0-9a-fA-F]+|0b[01]+|0o[0-7]+|\d+)\s*$/)
    raw_value
  else
    value.to_s
  end
end

def generate_svh(features, output_path)
  header = <<~HEADER
    // Generated from global_features.rb
    // Do not edit this file directly.
    `ifndef GLOBAL_FEATURES_SVH
    `define GLOBAL_FEATURES_SVH

  HEADER

  body = features.map do |feature|
    define_name = feature[:name].upcase
    value_text = format_feature_value(feature[:value], feature[:raw_value])
    "`define #{define_name} #{value_text}"
  end.join("\n")

  footer = <<~FOOTER

    `endif // GLOBAL_FEATURES_SVH
  FOOTER

  FileUtils.mkdir_p(File.dirname(output_path))
  File.write(output_path, [header, body, footer].join)
  puts "Generated #{output_path} with #{features.size} feature(s)."
  puts "\e[32mPASSED\e[0m -> Feature file generation"
end


def generate_header(features, output_path)
  guard_name = File.basename(output_path).upcase.gsub(/[^A-Z0-9]/, "_")

  header = <<~HEADER
    // Generated from global_features.rb
    // Do not edit this file directly.
    #ifndef #{guard_name}
    #define #{guard_name}

  HEADER

  body = features.map do |feature|
    define_name = feature[:name].upcase
    value_text = format_feature_value(feature[:value], feature[:raw_value])
    "#define #{define_name} #{value_text}"
  end.join("\n")

  footer = <<~FOOTER

    #endif // #{guard_name}
  FOOTER

  FileUtils.mkdir_p(File.dirname(output_path))
  File.write(output_path, [header, body, footer].join)
  puts "Generated #{output_path} with #{features.size} feature(s)."
  puts "\e[32mPASSED\e[0m -> Header file generation"
end

def generate_inc(features, output_path)
  header = <<~HEADER
    # Generated from global_features.rb
    # Do not edit this file directly.

  HEADER

  body = features.map do |feature|
    define_name = feature[:name].upcase
    value_text = format_feature_value(feature[:value], feature[:raw_value])
    ".set #{define_name}, #{value_text}"
  end.join("\n")

  FileUtils.mkdir_p(File.dirname(output_path))
  File.write(output_path, [header, body, "\n"].join)
  puts "Generated #{output_path} with #{features.size} feature(s)."
  puts "\e[32mPASSED\e[0m -> Assembler include generation"
end

def safe_join(base, *parts)
  if base.respond_to?(:/)
    parts.reduce(base) { |path, part| path / part }
  else
    File.join(base, *parts)
  end
end

def generate_feature_file()
  source = safe_join(ENV['STEM'], 'global_features.rb')
  svh_output = safe_join(ENV['OUT_HOME'], 'features', 'global_features.svh')
  header_output = safe_join(ENV['OUT_HOME'], 'features', 'global_features.h')
  inc_output = safe_join(ENV['OUT_HOME'], 'features', 'global_features.inc')

  unless File.exist?(source)
    abort "Missing source file: #{source}"
    false
  end

  features = parse_global_features(source)
  begin
    generate_svh(features, svh_output)
    generate_header(features, header_output)
    generate_inc(features, inc_output)
  rescue Errno::EACCES => e
    puts "\e[31mFAILED\e[0m -> Feature file generation"
    abort "Permission denied writing #{e.message}"
  end
end

if __FILE__ == $PROGRAM_NAME
  if env_check()
    system("bootenv")
  end
  generate_feature_file()
end

