def env_check
    if (ENV['STEM'] != __dir__)
        abort "Bootenv and retry!"
        false
    else
        puts "\e[32mPASSED\e[0m -> Bootenv check"
        true
    end
end

def parse_global_features(source_path)
  features = []
  parser = Object.new
  parser.define_singleton_method(:component) do |*_args, &block|
    instance_eval(&block) if block
  end

  parser.define_singleton_method(:feature) do |name, value|
    features << { name: name.to_s, value: value }
  end

  parser.instance_eval(File.read(source_path), source_path)
  features
rescue SyntaxError, StandardError => e
  abort "Failed to parse feature file #{source_path}: #{e.class}: #{e.message}"
end

require 'fileutils'

def generate_svh(features, output_path)
  header = <<~HEADER
    // Generated from global_features.rb
    // Do not edit this file directly.
    `ifndef GLOBAL_FEATURES_SVH
    `define GLOBAL_FEATURES_SVH

  HEADER

  body = features.map do |feature|
    define_name = feature[:name].upcase
    value = feature[:value]
    value_text = if value.is_a?(String)
      value.inspect
    else
      value.to_s
    end
    "`define #{define_name} #{value_text}"
  end.join("\n")

  footer = <<~FOOTER

    `endif // GLOBAL_FEATURES_SVH
  FOOTER

  FileUtils.mkdir_p(File.dirname(output_path))
  File.write(output_path, [header, body, footer].join)
  puts "Generated #{output_path} with #{features.size} feature(s)."
  puts "\e[32mPASSED\e[0m -> Feature file generation"
end

def safe_join(base, *parts)
  if base.respond_to?(:/)
    parts.reduce(base) { |path, part| path / part }
  else
    File.join(base, *parts)
  end
end

def generate_feature_file()
  source = safe_join(ENV['STEM'], 'global_features.rb')
  output = safe_join(ENV['OUT_HOME'], 'features', 'global_features.svh')

  unless File.exist?(source)
    abort "Missing source file: #{source}"
    false
  end

  features = parse_global_features(source)
  begin
    generate_svh(features, output)
  rescue Errno::EACCES => e
    puts "\e[31mFAILED\e[0m -> Feature file generation"
    abort "Permission denied writing #{output}: #{e.message}"
  end
end

if __FILE__ == $PROGRAM_NAME
  env_check()
  generate_feature_file()
end

