require_relative '../run'

env_check()

def parse_global_features(source_path)
  features = []
  File.readlines(source_path).each_with_index do |line, index|
    next unless line =~ /feature\s+["']([^"']+)["']\s*,\s*(\d+)/
    features << { name: Regexp.last_match(1).strip, value: Regexp.last_match(2).to_i }
  rescue StandardError => e
    warn "Failed to parse feature on line #{index + 1}: #{e.message}"
  end
  features
end

require 'fileutils'

def generate_svh(features, output_path)
  header = <<~HEADER
    // Generated from src/global_features.rb
    // Do not edit this file directly.
    `ifndef GLOBAL_FEATURES_SVH
    `define GLOBAL_FEATURES_SVH

  HEADER

  body = features.map do |feature|
    define_name = feature[:name].upcase
    "`define #{define_name} #{feature[:value]}"
  end.join("\n")

  footer = <<~FOOTER

    `endif // GLOBAL_FEATURES_SVH
  FOOTER

  FileUtils.mkdir_p(File.dirname(output_path))
  File.write(output_path, [header, body, footer].join)
  puts "Generated #{output_path} with #{features.size} feature(s)."
end

def safe_join(base, *parts)
  if base.respond_to?(:/)
    parts.reduce(base) { |path, part| path / part }
  else
    File.join(base, *parts)
  end
end

def generate_feature_file()
  source = safe_join(ENV['STEM'], 'src', 'global_features.rb')
  output = safe_join(ENV['OUT_HOME'], 'features', 'global_features.svh')

  unless File.exist?(source)
    abort "Missing source file: #{source}"
  end

  features = parse_global_features(source)
  begin
    generate_svh(features, output)
  rescue Errno::EACCES => e
    fallback_root = safe_join(File.expand_path('..', __dir__), 'out', 'features')
    fallback_output = safe_join(fallback_root, 'src', 'global_features.svh')
    warn "Permission denied writing #{output}; writing generated file to #{fallback_output} instead."
    generate_svh(features, fallback_output)
  end
end

